### ISSUE TITLE
Alternative way of publishing continuous builds

### ISSUE THREAD

**Issue by nurupo** [probonopd/uploadtool#32]
Just sharing something I have learned that you might be interested in knowing, assuming you don't know it already. Note that I'm not proposing any change or pointing out any bug in uploadtool.

I have recently learned that GitHub's wiki is also a git repository, and you can setup Travis-CI to upload nightly builds on each commit to some file sharing service (potentially signed by some Travis gpg key) and update wiki with those download links. [Here is an example](https://github.com/martinrotter/textosaurus/wiki/Development-builds) of someone doing this ([this seems to be the code](https://github.com/martinrotter/textosaurus/blob/master/resources/scripts/.travis-install-linux.sh)).

Pros:
- uploadtool keeps only the last builds files, using a wiki you can check previous revisions and find builds of previous commits

Cons:
- It's not on Releases page (though you could link to the wiki page in the release notes)
- File sharing services don't keep files for long, generally a month or so, while GitHub seems to keep the forever

**Comment by probonopd** [comment]
Thanks for letting us know @nurupo.
