### ISSUE TITLE
Firefox Send as a replacement for transfer.sh

### ISSUE THREAD

**Issue by probonopd** [probonopd/uploadtool#43]
With transfer.sh getting less reliable, we may want to look into Firefox Send as a replacement for transfer.sh.

https://github.com/ehuggett/send-cli

https://send.firefox.com/

**Comment by Holyprogrammer** [comment]
I find [ffsend](https://github.com/timvisee/ffsend) to be more reliable than send-cli

**Comment by qwertychouskie** [comment]
Firefox Send has been dead for years now, this issue should be closed.
