### ISSUE TITLE
Upload certain files as executable

### ISSUE THREAD

**Issue by bengtmartensson** [probonopd/uploadtool#48]
It would be advantageous to keep certain files, that the downloading user is suppose to execute (for example `*.AppImage` and `*.sh`), as executable in the sense of Unix (chmod +x) on Github. So I am requesting a way to "chmod +x" a just uploaded file, if for example the file matches a particular pattern (`*.AppImage`, `*.sh`, ...). Or just to preserve the permission flags would also work (curl by nature squishes them).

**Comment by probonopd** [comment]
Unfortunately uploading to http(s) does not preserve permissions.

Users need to use https://github.com/AppImage/appimaged or similar tools if they want their AppImages to be set executable automatically.

**Comment by bengtmartensson** [comment]
Ok. Github (which is not just http) has some "limitations".
Possibly we will find a solution in the future.
