### ISSUE TITLE
uploading large file fails

### ISSUE THREAD

**Issue by mmtrt** [probonopd/uploadtool#51]
```
Upload binaries to the release...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 2392M  100   246    0     0    647      0 --:--:-- --:--:-- --:--:--   645
{"message":"Validation Failed","request_id":"xxx:xxx:xxxx:xxxxx:xxxxxxxx","documentation_url":"https://developer.github.com/v3","errors":[{"resource":"ReleaseAsset","code":"custom","field":"size","message":"size is not included in the list"}]}
```

Does it need some more permissions for token?
currently have only checked repo section only.

**Comment by probonopd** [comment]
Never seen this issue before.

But I have also never tried to upload files that large. Does it work when you upload using the GitHub Releases GUI?

And are we sending the correct  `content-length` header?

**Comment by mmtrt** [comment]
I don't have fast upload speed that would take ages to upload so I'm still I'm doing similar work related to your forked repo `system` which has custom iso file upload not sure its done via script or manually.

when some changes were not working in my repo it did upload `original.iso` file fine without any issues which was large and now with correct changes it not uploading iso but does `zsync` and some `source.zip` files.

Some days ago I did tried with new fresh repos build similar work under different names had same issue still I'm not sure why is this happening with this.

or I should use you fork repo and do my changes see if that works.

**Comment by probonopd** [comment]
Sure, feel free too fork and experiment. Let us know one you have something that is working for you.

**Comment by mmtrt** [comment]
Seems like there is size limit `2G` that is why it is failing & if its less then that file uploads fine.
