### ISSUE TITLE
Release notification being generated for every rebuild

### ISSUE THREAD

**Issue by justinclift** [probonopd/uploadtool#6]
We've discovered an unfortunate side effect of the current upload script. :wink:

Every time it runs, everyone watching our project is getting spammed by a new "release notification".
eg for every single commit we do

It's becoming pretty annoying. 😦 

Looking through the upload script (and now afterwards, reading the readme) it's recreating the release every time.

That might be workable for low churn projects... but it's not really a go-er for us.

Any thoughts on how to avoid this problem, apart from just stopping these Continuous builds?

**Comment by justinclift** [comment]
Ahhhh, this seems like a duplicate of #1.  I'll try the `.travis.yml` solution mentioned [there](https://github.com/probonopd/uploadtool/issues/1#issuecomment-259818295).

**Comment by justinclift** [comment]
As a follow up data point, all attempts to suppress the release notification spam using settings in the .travis.yml failed.

Instead, we switched to using the upload script by @aferrero2707, which works and we're no longer getting spammed.  Thanks @aferrero2707. :smile:

**Comment by probonopd** [comment]
@aferrero2707 mind to share your secret sauce? ;-)

**Comment by aferrero2707** [comment]
I've not answered because I feel dumb... honestly speaking, I do not remember anymore which sauce I cooked for this script!!!

I remember having spent quite some time in trying to get the script reliable, as from time to time the submit requests were not completed on the github side. 

Next I started working on a new script that automatically deletes old files, and only keeps the 5 newest ones, but never had time to test and validate this second script in detail.

Anyway, my repo is a fork of yours, so let me create a PR and then you can check what good things you can keep from it for dessert ;-)

**Comment by probonopd** [comment]
Thank you @aferrero2707. Let's collect some feedback from users and then I'll gladly merge it!

**Comment by justinclift** [comment]
Ahhh.  The difference between the scripts, at least as far as stopping the notification spam, is that @aferrero2707's doesn't recreate the issue each time.  Instead it locates the existing issue (if there is one) and just replaces the old binaries.

Nothing rocket science-y about it, just appropriate functionality for the task needing doing. :smile:

**Comment by probonopd** [comment]
Issue? You mean Release? But is the Release then linked to the correct commit?

**Comment by aferrero2707** [comment]
No, indeed the commit reference is not updated in this case. Personally I was not particularly interested in this, as I use the continuous release as a placeholder for development snapshots, some of which are not generated via Travis CI.

**Comment by justinclift** [comment]
Oops, yep I meant "Release" not issue.  As with @aferrero2707, for us it's more important to just have a release people can download + not get spammed for each commit.  Having it associated to the matching commit is minor.

If some way can be found to also have it matching the right commit, then sure, that would be useful.  But the "not generating release notification each time" is WAY more important (to us). :smile:

**Comment by probonopd** [comment]
> No, indeed the commit reference is not updated in this case. 

OK, that might be a killer for some people (including myself) then. I think it is the whole point of a continuous build pipeline to always have a direct link between the build artefacts and the source code commit that produced them. The "spam" (as you call it) is not something that ever worried _me_ - after all, I voluntarily _subscribed_ to it (but of course others might value this differently).

**Comment by justinclift** [comment]
> I voluntarily subscribed to it (but of course others might value this differently).

Yep.  People definitely do "Watch" repo's for specific reasons.  I've already been in contact with GitHub staff to find out if there's a way to suppress release notifications, even if on only a specific repo.  There isn't, so... some way around that is definitely needed for some users. :smile:
