### ISSUE TITLE
Overwrite same commit

### ISSUE THREAD

**Issue by qurious-pixel** [probonopd/uploadtool#68]
How do you overwrite the same commit?

Can I comment out line #271 
`if [ "$TRAVIS_COMMIT" != "$tag_sha" ] ; then`

I want it overwrite the same commit if the build is successful.

**Comment by probonopd** [comment]
Consider https://github.com/tcnksm/ghr as an alternative.

It is written in Go, probably more robust, and configurable.

And it can do what you are asking for, I think.

**Comment by qurious-pixel** [comment]
Thanks for the tip. Used the repo in my project.

**Comment by qurious-pixel** [comment]
to recreate the upload.sh functionality with overwrite, I used the following:
`ghr -recreate -n 'Continous build' -b "Travis CI build log ${TRAVIS_BUILD_WEB_URL}" continuous artifacts/`

in the format of `ghr [option] TAG [PATH]`
