### ISSUE TITLE
How to upload latest GitHub Actions artifacts as `continuos` pre-release asset

### ISSUE THREAD

**Issue by Symbian9** [probonopd/uploadtool#72]
As *Bintray* storage discontinued, *FontForge* needs should be switched to storing build artifacts (i.e. nightly *AppImage*) as assets for `continuous` pre-release.

- https://github.com/fontforge/fontforge.github.io/issues/162

Here are GitHub Actions workflow scripts:

- https://github.com/fontforge/fontforge/tree/master/.github/workflows

How to setup those scripts (+ `uploadtool`) to upload latest *AppImage* builds as assets for `continuous` pre-release?

**Comment by probonopd** [comment]
There are readymade solutions for this like https://github.com/fnkr/github-action-ghr
